### ISSUE TITLE
do you have binary (executable) which could run directly in Windows10?

### ISSUE THREAD

**Issue by rayeaster** [xf97/SolidityCheck#1]
a release version with executable could save compilation effort for some interesting users maybe

**Comment by xf97** [comment]
Sorry, due to the limitations of our development environment, we are temporarily unable to provide you with .exe files. Fortunately, SolidityCheck was originally developed on win10 and later ported to ubuntu for development. We tested the usability on win10 (It's ok), which means that it is feasible to compile the source code on win10. (According to our test, there will be some compilation errors on win10, those are errors caused by comments or output string garbled, you can manually delete these garbled strings)

**Comment by xf97** [comment]
@rayeaster Closed
